### ISSUE TITLE
Feature: User registration and authentication

### ISSUE THREAD

**Issue by mzmoosa01** [mzmoosa01/DigitalAlbum#3]
# Epic Title

Feature: User registration and authentication

## Epic Description

This Feature will allow users to register on the system and will protect Api routes from non-authenticated users. 

## List of Tasks 

1. [ ] Setup initial individual authentication #4 
2. [ ] Setup email verification #5 
3. [ ] Add password recovery mechanism #6
