### ISSUE TITLE
Feature: image CRUD operations

### ISSUE THREAD

**Issue by mzmoosa01** [mzmoosa01/DigitalAlbum#7]
# Epic Title

Feature: CRUD operations

## Epic Description

This Feature will enable all CRUD features with regards to images

## List of Tasks (Complete in order)

1. [ ] Enable uploading of images to s3 bucket #8 
2. [ ] Enable fetching of images #9 
3. [ ] Enable deletion of images #10 
4. [ ] Enable searching of images by title #11 
5. [ ] Enable updating of image metadata #12
